resa_homepage:
    path:     /
    defaults: { _controller: ResaBundle:Default:index }

resa_formpage:
    path:     /resa
    defaults: { _controller: ResaBundle:Resa:form }

resa_commandpage:
    path:     /commande
    defaults: { _controller: ResaBundle:Commande:commande }
