resa_homepage:
    path:     /
    defaults: { _controller: ResaBundle:Default:index }

resa_formpage:
    path:     /resa
    defaults: { _controller: ResaBundle:Resa:form }

resa_commandpage:
    path:     /commande
    defaults: { _controller: ResaBundle:Commande:commande }

resa_script:
    path: /resa_script
    defaults: { _controller: ResaBundle:Resa:script }

resa_scriptFerie:
    path: /resa_scriptFerie
    defaults: { _controller: ResaBundle:Resa:scriptFerie }
