services:
#    resa.example:
#        class: ResaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    resa.tarif:
        class: ResaBundle\Tarif
        arguments: ['%tarifs%']

    resa.jourFerie:
        class: ResaBundle\JourFerie
        arguments:
